name: Render Rmd files and deploy

on:
  push:
    branches: [ main, gh-actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Setup git config
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "<>"
      - name: Install packages
        run: |
          Rscript -e 'install.packages("rmarkdown")'
          Rscript -e 'install.packages("bookdown")'
      - name: Render Rmd files
        run: ./build.sh
      - name: Update gh-pages
        run: ./deploy.sh
