name: Render Rmd files and deploy

on:
  push:
    branches: [ main, gh-actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render Rmd files
        run: Rscript -e "bookdown::render_book('mrs-educational-book/index.Rmd', 'bookdown::gitbook', output_dir = 'book')"
