name: Render Rmd files and deploy

on:
  push:
    branches: [ main, gh-actions ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Github action for rmarkdown
        uses: lucharo/rmarkdown-action@v1
        with:
          input_file: index.Rmd
          output_format: html_document
